swiftmailer:
    transport: '%env(MAILER_TRANSPORT)%'
    host:      '%env(MAILER_HOST)%'
    username:  '%env(MAILER_USER)%'
    password:  '%env(MAILER_PASSWORD)%'
    spool:     { type: memory }
    encryption: ssl
    #TODO: One day we are going to use "url" instead all the above.
    #url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
