twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    form_themes:
        # Forms are automatically constructed.
        # With this switch, we can use BOOTSTRAP (Yay!)
        # (we can even go further! see https://symfony.com/doc/current/book/forms.html#id1)
        - bootstrap_3_layout.html.twig
        #- bootstrap_3_horizontal_layout.html.twig
    globals:
        #TODO enable this again
        flash: "@App\\Service\\Flash\\FlashService"
