#<command to execute>
cmd: "powershell"
#<name of target>
name: "Sandbox"
args:
  - "-File"
  - "{PROJECT_PATH}/deploy/sandbox.ps1"
sh: false
#<current working directory for `cmd`>
cwd: "{PROJECT_PATH}/deploy/"
#env:
#  VARIABLE1: "VALUE1"
#  VARIABLE2: "VALUE2"
#errorMatch:
#  - ^regexp1$
#  - ^regexp2$
#warningMatch:
#  - ^regexp1$
#  - ^regexp2$
#keymap: <keymap string>
#atomCommandName: namespace:command
targets:
    DEV.01.CleanAndLoad:
        cmd: "powershell"
        args:
          - "-File"
          - "{PROJECT_PATH}/deploy/01cleanAndLoad.ps1"
          - "-env"
          - "dev"
          - "-projectPath"
          - "{PROJECT_PATH}"
          - "-Verbose"
        sh: false
        #<current working directory for `cmd`>
        cwd: "{PROJECT_PATH}/deploy/"
    DEV.02.Build:
        cmd: "powershell"
        args:
          - "-File"
          - "{PROJECT_PATH}/deploy/02build.ps1"
          - "-env"
          - "dev"
          - "-projectPath"
          - "{PROJECT_PATH}"
          - "-Verbose"
        sh: false
        #<current working directory for `cmd`>
        cwd: "{PROJECT_PATH}/deploy/"
    DEV.03.Webpack:
        cmd: "powershell"
        args:
          - "-File"
          - "{PROJECT_PATH}/deploy/03webpack.ps1"
          - "-env"
          - "dev"
          - "-projectPath"
          - "{PROJECT_PATH}"
          - "-Verbose"
        sh: false
        #<current working directory for `cmd`>
        cwd: "{PROJECT_PATH}/deploy/"
    DEV.04.FinishAndCleanup:
        cmd: "powershell"
        args:
          - "-File"
          - "{PROJECT_PATH}/deploy/04finishAndCleanup.ps1"
          - "-env"
          - "dev"
          - "-projectPath"
          - "{PROJECT_PATH}"
          - "-Verbose"
        sh: false
        #<current working directory for `cmd`>
        cwd: "{PROJECT_PATH}/deploy/"
    PROD.01.CleanAndLoad:
        cmd: "powershell"
        args:
          - "-File"
          - "{PROJECT_PATH}/deploy/01cleanAndLoad.ps1"
          - "-env"
          - "prod"
          - "-projectPath"
          - "{PROJECT_PATH}"
          - "-Verbose"
        sh: false
        #<current working directory for `cmd`>
        cwd: "{PROJECT_PATH}/deploy/"
    PROD.02.Build:
        cmd: "powershell"
        args:
          - "-File"
          - "{PROJECT_PATH}/deploy/02build.ps1"
          - "-env"
          - "prod"
          - "-projectPath"
          - "{PROJECT_PATH}"
          - "-Verbose"
        sh: false
        #<current working directory for `cmd`>
        cwd: "{PROJECT_PATH}/deploy/"
    PROD.03.Webpack:
        cmd: "powershell"
        args:
          - "-File"
          - "{PROJECT_PATH}/deploy/03webpack.ps1"
          - "-env"
          - "prod"
          - "-projectPath"
          - "{PROJECT_PATH}"
          - "-Verbose"
        sh: false
        #<current working directory for `cmd`>
        cwd: "{PROJECT_PATH}/deploy/"
    PROD.04.FinishAndCleanup:
        cmd: "powershell"
        args:
          - "-File"
          - "{PROJECT_PATH}/deploy/04finishAndCleanup.ps1"
          - "-env"
          - "prod"
          - "-projectPath"
          - "{PROJECT_PATH}"
          - "-Verbose"
        sh: false
        #<current working directory for `cmd`>
        cwd: "{PROJECT_PATH}/deploy/"
