app_web:
    resource: "@AppBundle/Controller/"
    type:     annotation

api_api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
