# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    user_register_listener:
        class: AppBundle\EventListener\UserRegistrationConrimedListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }

    app.form.profile:
        class: AppBundle\Form\ProfileFormType
        arguments: ["\\AppBundle\\Entity\\User"]
        tags:
            - { name: form.type, alias: app_user_profile }

    app.auth:
        class: AppBundle\Service\Authorization
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@security.authorization_checker"]

    app.event:
        class: AppBundle\Service\EventService
        arguments: ["@app.auth", "@doctrine.orm.entity_manager"]
