# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\: #namespace
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller/*'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #TODO this service override the one from FosUserBundle, since it is not yet ready for symfony 4.0
    #TODO Remove it as soon as FosUserBundle is updated.
    fos_user.profile.form.factory:
        class: 'FOS\UserBundle\Form\Factory\FormFactory'
        arguments: ["@form.factory", '%fos_user.profile.form.name%', '%fos_user.profile.form.type%', '%fos_user.profile.form.validation_groups%']
        public: true

    AppBundle\Service\EventService:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@AppBundle\\Service\\IAuthorizationService"
            - "@AppBundle\\Service\\IDepartmentService"
            - "@AppBundle\\Service\\ICommitmentService"
            - "@AppBundle\\Service\\IQuestionService"

    AppBundle\EventListener\UserRegistrationListener:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    AppBundle\Form\ProfileFormType:
        arguments: ["\\AppBundle\\Entity\\User"] # keep this.
        tags:
            - { name: form.type, alias: app_user_profile }

    AppBundle\Service\DepartmentService:
        arguments:
            - "@AppBundle\\Service\\IAuthorizationService"
            - "@doctrine.orm.entity_manager"

    AppBundle\Service\MenuService:
        arguments:
            - "@AppBundle\\Service\\IAuthorizationService"

    AppBundle\Service\Flash\FlashService:
        arguments: ["@session"]

    AppBundle\Service\AuthorizationService:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
            - "@security.authorization_checker"

    AppBundle\Service\MailBuilderService:
        arguments: ["@twig"]

    AppBundle\Service\SettingsService:
        arguments: ["@doctrine.orm.entity_manager"]

    AppBundle\Service\QuestionService:
        arguments: ["@doctrine.orm.entity_manager"]

    AppBundle\Service\CommitmentService:
        arguments:
            - "@AppBundle\\Service\\IAuthorizationService"
            - "@doctrine.orm.entity_manager"
            - "@logger"

    AppBundle\Service\UserService:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@translator"
